<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Вход</title>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <link rel="stylesheet" href="./view/css/bootstrap.css">
    <link rel="stylesheet" href="./view/css/bootstrap-grid.css">
    <link rel="stylesheet" href="./view/css/bootstrap-reboot.css">
</head>
<body>

<ul class="nav justify-content-end" id="nav">
    <li class="nav-item">
        <a id="getRegister" class="nav-link active" href="index.php?getReg=1">Регистрация</a>
    </li>
</ul>
<div class="container-fluid">
    <div class="row justify-content-center align-items-center" id="mainBlock">
        <div class="col-2">
            <form id="loginForm">
                <div class="form-group">
                    <label for="InputLogin">Логин</label>
                    <input name="login" type="text" class="form-control" id="InputLogin" aria-describedby="loginHelp" placeholder="Введите логин">
                    <small id="loginHelp" class="form-text text-muted text-danger text-hide">Логин не соответствует требованиям</small>
                </div>
                <div class="form-group">
                    <label for="InputPassword1">Пароль</label>
                    <input name="password" type="password" class="form-control" id="InputPassword1" placeholder="Введите пароль">
                    <small id="passwordHelp" class="form-text text-muted text-danger text-hide">Пароль не соответствует требованиям</small>
                </div>
                <button type="submit" class="btn btn-primary">Войти</button>
            </form>
            <div id="vvv">

            </div>
        </div>
    </div>
</div>


<!--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<script src="./view/js/jquery-3.5.1.js"></script>
<script src="./view/js/js.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->
<script src="./view/js/bootstrap.js"></script>

</body>
</html>