<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Вход</title>
    <link rel="stylesheet" href="./view/css/bootstrap.css">
    <link rel="stylesheet" href="./view/css/bootstrap-grid.css">
    <link rel="stylesheet" href="./view/css/bootstrap-reboot.css">
</head>
<body>
<ul class="nav justify-content-end" id="nav">
    <li class="nav-item">
        <a id="getRegister" class="nav-link active" href="index.php?out=1">Выйти</a>
    </li>
</ul>
<div class="container-fluid">
    <div class="row justify-content-center align-items-center" id="mainBlock">
        <div class="col-2">
            <h1><?= $hey;?></h1>
        </div>
    </div>
</div>
<script src="./view/js/jquery-3.5.1.js"></script>
<script src="./view/js/js.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="./view/js/bootstrap.js"></script>
</body>
</html>