<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Регистрация</title>
    <link rel="stylesheet" href="./view/css/bootstrap.css">
    <link rel="stylesheet" href="./view/css/bootstrap-grid.css">
    <link rel="stylesheet" href="./view/css/bootstrap-reboot.css">
</head>
<body>
<ul class="nav justify-content-end" id="nav">
    <li class="nav-item">
        <a id="getRegister" class="nav-link active" href="index.php?getReg=0">Войти</a>
    </li>
</ul>
<div class="container-fluid">
    <div class="row justify-content-center align-items-center" id="mainBlock">
        <div class="col-2">
            <form id="regForm">
                <div class="form-group">
                    <label for="InputLogin">Логин</label>
                    <input name="login" type="text" class="form-control required" id="InputLogin" aria-describedby="loginHelp" placeholder="Введите логин" required>
                    <small id="loginHelp" class="form-text text-muted text-danger text-hide">Логин не соответствует требованиям или уже используется</small>
                </div>
                <div class="form-group">
                    <label for="InputPassword1">Пароль</label>
                    <input name="password" type="password" class="form-control" id="InputPassword1" placeholder="Введите пароль" required>
                    <small id="passwordHelp" class="form-text text-muted text-danger text-hide">Пароль не соответствует требованиям</small>
                </div>
                <div class="form-group">
                    <label for="InputPassword2">Повторите пароль</label>
                    <input name="repassword" type="password" class="form-control" id="InputPassword2" placeholder="Повторите пароль" required>
                    <small id="repasswordHelp" class="form-text text-muted text-danger text-hide">Пароли не совпадают</small>
                </div>
                <div class="form-group">
                    <label for="InputEmail">Email</label>
                    <input name="email" type="email" class="form-control" id="InputEmail" placeholder="Введите email" required>
                    <small id="emailHelp" class="form-text text-muted text-danger text-hide">Email не соответствует требованиям или уже используется</small>
                </div>
                <div class="form-group">
                    <label for="InputName">Ваше имя</label>
                    <input name="fname" type="text" class="form-control" id="InputName" placeholder="Введите свое имя" required>
                    <small id="nameHelp" class="form-text text-muted text-danger text-hide">Имя не соответствует требованиям</small>
                </div>
                <button type="button" id="regAct" class="btn btn-primary">Регистрация</button>
            </form>
        </div>
    </div>
</div>
<script src="./view/js/jquery-3.5.1.js"></script>
<script src="./view/js/js.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="./view/js/bootstrap.js"></script>
</body>
</html>